version: '3'

services:
  spring-demo-app:
    build:
      context: ./../employermanager
      dockerfile: Dockerfile.dev
    image: spring-demo-app
    container_name: spring-demo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - dev-network

  db:
    build:
      context: ./config/mysql
      dockerfile: Dockerfile.dev
    image: dev-mysql
    container_name: dev-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33601:3306"
    environment:
      MYSQL_DATABASE: dev-mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./db-mysql:/var/lib/mysql/
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge

